# Generated by Django 5.1.6 on 2025-02-23 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tradingapp', '0004_remove_buystock_stock_remove_buystock_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioitem',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='portfolioitem',
            name='user',
        ),
    ]
